
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - ./data/mongo:/data/db

  nest:
    build: .
    container_name: nest-app
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo_data:
